DROP TABLE BNKSPA;
COMMIT;

CREATE TABLE BNKSPA
(
    BSP_TERM               CHAR(8) NOT NULL,
    BSP_SPA_DATA           VARCHAR(6144) NOT NULL
)
IN DBNASE.SPA
AUDIT NONE
DATA CAPTURE NONE;

COMMIT;
