DEL ZBNKALL.SQL

TYPE ZDBNASE.SQL   > ZBNKALL.SQL

TYPE ZBNKATYP.SQL >> ZBNKALL.SQL
TYPE ZBNKCUST.SQL >> ZBNKALL.SQL
TYPE ZBNKACC.SQL  >> ZBNKALL.SQL
TYPE ZBNKTXN.SQL  >> ZBNKALL.SQL
TYPE ZBNKDETS.SQL >> ZBNKALL.SQL
TYPE ZBNKHELP.SQL >> ZBNKALL.SQL
TYPE ZBNKSPA.SQL  >> ZBNKALL.SQL


